device: /dev/ttyACM0

uart1:
  baudrate: 115200

frame_id: gps
rate: 20
nav_rate: 1
enable_ppp: false
gnss:
  sbas: true
  gps: true
  glonass: true
  beidou: false
  qzss: false

nmea:
  set: true
  version: 65
  num_sv: 8
  compat: true
  consider: true
  limit82: true
  high_prec: false
  sv_numbering: 1
  filter:
    pos: true
    msk_pos: true
    time: true
    date: true
    sbas: true
    gps_only: false
    track: true
  gnssToFilt:
    gps: false
    sbas: false
    qzss: true
    glonass: false
    beidou: true
  main_talker_id: 1
  gsv_talker_id: 1
  bds_talker_id: [0,0]

sbas:
  max: 0
  usage: 0

dynamic_model: automotive
fix_mode: auto
